#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

picom &
firefox &
# delay thunderbird to allow protonmail initialize and avoid thunderbirds' "no connection to 127.0.0.1"
protonmail-bridge --no-window & ( sleep 5 && thunderbird & )
signal-desktop &
telegram-desktop &
redshift -l40:2 &
syncthing &
xfce4-power-manager &


/usr/bin/dwm
