#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# setting keyboard layout and more; check it for more info
dunst &			# dunst for notifications
