#!/bin/bash

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.


# generate .Xresources
$HOME/.local/bin/genxresources > $HOME/.Xresources
xrdb $HOME/.Xresources
xrdbpid=$!

# Ensure that xrdb has finished running before using xrdb and moving on to WM/DE
[ -n "$xrdbpid" ] && wait "$xrdbpid"

# generate zathura config with colors from .Xresources
mkdir -pv $HOME/.config/zathura && $HOME/.local/bin/genzathurarc > $HOME/.config/zathura/zathurarc

# and dunst too
mkdir -pv $HOME/.config/dunst && $HOME/.local/bin/gendunstrc > $HOME/.config/dunst/dunstrc

$HOME/.local/bin/setbg

$HOME/.local/bin/remaps

autostart=(
	"xcompmgr"
	"mpd"
	"dunst"
	"unclutter"
	"gentoo-pipewire-launcher"
	"syncthing --no-browser"
	"dwmblocks"
	"redshift -l40:2"
)

for program in "${autostart[@]}" ; do
	pidof -s "${program%% *}" || setsid -f $program
done >$XDG_CACHE_HOME/xprofile.errors 2>&1

if [ -x /usr/bin/gpg-agent ]; then
	eval "$(/usr/bin/gpg-agent --daemon)"
fi
