#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim='nvim' vimdiff='nvim -d'

# sudo not required for some system commands
for command in su ; do
    alias $command='sudo $command'
done; unset command

# allow calls of aliases by xargs
alias xargs='xargs '

# workaround sudo's PATH change
# https://stackoverflow.com/questions/257616/why-does-sudo-change-the-path
alias sudo='sudo env PATH=$PATH'

# Verbosity and settings that you pretty much just always are going to want.
alias \
        cp='cp -iv' \
        mv='mv -iv' \
        rm='rm -vI' \
        mkd='mkdir -pv' \
        yt='youtube-dl --add-metadata -i' \
        yta='yt -x -f bestaudio/best' \
        ffmpeg='ffmpeg -hide_banner' \
    	nnn='nnn -deARU'

# Colorize commands when possible.
alias \
        ls='ls -hN --color=auto --group-directories-first' \
        grep='grep --color=auto' \
        diff='diff --color=auto' \
        ccat='highlight --out-format=ansi'


alias \
        yt='youtube-dl --add-metadata -ic' \
        yta='youtube-dl --add-metadata -xic' \
        ka='killall' \
        g='git' \
        f='$FILE' \
        ssd='systemctl shutdown' \
        ssp='systemctl suspend' \
        e='$EDITOR' \
        v='$EDITOR' \
        a='sudo apt' \
        z='zathura'

# spawn detached terminal
alias dst='"$TERMINAL" </dev/null &>/dev/null & disown ;'

# run mpv with SVP, if SVP not active, works as usual mpv
alias mpv60='if [ -n $(pidof SVPManager) ]; then $HOME/.local/bin/svpman & fi ; mpv --input-ipc-server=/tmp/mpvsocket --hwdec=auto-copy'

# pass files selected in nnn to a program
# e.g. "nsel mpv60" to play multiple videos one after another
nsel_internal() {
    cat "${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}" | \
    tr '\0' '\n' | awk 'NF { print "\""$0"\""}' | tr '\n' ' '
}
alias nsel='nsel_internal | xargs '

alias detach='bg && disown'

# window swallowing, also autoplay gifs in sxiv
alias sxiv='devour sxiv -a'
alias mpv='devour mpv'
alias zathura='devour zathura'

# required for $HOME cleanup
alias nvidia-settings='nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings'
alias wget='wget --hsts-file=$XDG_CACHE_HOME/wget-hsts'
alias yarn='yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config'

#alias monerod='monerod --data-dir $XDG_DATA_HOME/bitmonero'
#alias monero-wallet-cli='monero-wallet-cli --wallet-file $XDG_DATA_HOME/bitmonero/monero-wallet'

#alias wttr='curl https://wttr.in/paris-france'

[ -d "$XDG_CONFIG_HOME/abook/" ] || mkdir -p "$XDG_CONFIG_HOME/abook/"
[ -d "$XDG_DATA_HOME/abook/" ] || mkdir -p "$XDG_DATA_HOME/abook/"
alias abook='abook --config $XDG_CONFIG_HOME/abook/abookrc --datafile $XDG_DATA_HOME/abook/addressbook'

alias beet='$XDG_DATA_HOME/venv/beets/bin/beet'

# https://unix.stackexchange.com/questions/224227/how-do-you-make-an-alias-or-function-that-retains-tab-completion
# First find out which complete-function is used for the systemctl command:
#   complete | grep " systemctl$"
# The output looks like this:
#   complete -F _functionname systemctl
# Then use:
#   complete -F _functionname sctl
# To register the function for the completion of your alias.

# beet completion is lazy and will only load after <Tab>ing the actual command
# load manually then
# source /usr/share/bash-completion/completions/<whatever>



# due to how terminal works, this will echo and then type the command
# 'tput el1; echo' will erase the echo, leaving previous line blank
alias fzh='xdotool type "$(grep -v '^#' $XDG_STATE_HOME/bash_history | uniq -u | fzf --tac)"; tput el1; echo'
