#!/bin/sh

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022


[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"

export PATH="$PATH:$(du -L "$HOME/.local/bin" | cut -f2 | paste -sd ':')"

# automatically logout after some time
#export TMOUT=300
#readonly TMOUT
#export TMOUT

export PAGER="less"
export EDITOR="nvim"
export TERMINAL="st"

export BROWSER="firefox"
if command -v firefox-bin &> /dev/null
then
    export BROWSER="firefox-bin"
fi

export READER="zathura"

#export XDG_CACHE_HOME="$HOME/.cache"
# EXPERIMENTAL
export XDG_CACHE_HOME="$XDG_RUNTIME_DIR/.cache"
mkdir -p $XDG_CACHE_HOME
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"


# Eternal bash history.
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
#export HISTFILE=~/.bash_eternal_history
export HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/bash_history"
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"


# cleaning up
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"
export WINEPREFIX="${XDG_DATA_HOME:-$HOME/.local/share}/wineprefixes/default"
export TEXMFHOME=$XDG_DATA_HOME/texmf
export TEXMFVAR=$XDG_CACHE_HOME/texlive/texmf-var
export TEXMFCONFIG=$XDG_CONFIG_HOME/texlive/texmf-config
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export KLAYOUT_HOME=$XDG_DATA_HOME/klayout
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export SSB_HOME="$XDG_DATA_HOME"/zoom
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/password-store"
export SUDO_ASKPASS="$HOME/.local/bin/pass-askpass"
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export W3M_DIR="$XDG_STATE_HOME/w3m"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
# xinit
#export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XSERVERRC="$XDG_CONFIG_HOME/x11/xserverrc"
# X server
export USERXSESSION="$XDG_CONFIG_HOME/x11/xsession"
export USERXSESSIONRC="$XDG_CONFIG_HOME/x11/xsessionrc"
export ALTUSERXSESSION="$XDG_CONFIG_HOME/x11/Xsession"
export ERRFILE="$XDG_STATE_HOME/x11/xsession-errors"
# it is more trouble than it's worth
#export XAUTHORITY="$XDG_CACHE_HOME"/Xauthority
# libx11
export XCOMPOSEFILE="$XDG_CONFIG_HOME/x11/xcompose"
export XCOMPOSECACHE="$XDG_CACHE_HOME/x11/xcompose"
export PYENV_DIR="$XDG_DATA_HOME/pyenv"
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"

# POSIX standard says: send read local mail to ~/mbox, an mbox database
# gentoo uses maildir by default, it is also recommended over mbox
# setting $MBOX to maildir/cur will treat it as a file, which does not help
# so override standard to avoid a mess
export MAIL="$XDG_DATA_HOME/mail/$USER@localhost/INBOX"
# also override mailutils's mail as it will create it's own mail directory
alias mail='mutt -f $MAIL'
# bash will also detect new mail in $MAIL every $MAILCHECK seconds (60 by default)
export MAILCLIENT="mutts"

export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export MBSYNCRC="${XDG_CONFIG_HOME:-$HOME/.config}/mbsync/config"
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export TMUX_TMPDIR="$XDG_CACHE_DIR"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"

# who needs history from less? no one
export LESSHISTFILE="-"
# retain color (maybe useless, most commands remove color when outputting to pipe, which is reasonable)
export LESS=-R
# but we can counter that with highlight
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
# colorize special text:
# begin blinking
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
# begin bold
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
# end mode
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
# begin standout-mode
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
# end standout-mode
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
# begin underline
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
# end underline
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

# Have QT use gtk2 theme.
export QT_QPA_PLATFORMTHEME="gtk2"
export QT_STYLE_OVERRIDE="gtk2"

# don't start GTK3 garbage
export NO_AT_BRIDGE=1

# Mozilla smooth scrolling/touchpad support
export MOZ_USE_XINPUT2="1"

# nnn things
# https://github.com/jarun/nnn/wiki/Usage#configuration
export NNN_BMS='v:~/vid;p:~/pix;d:~/dox;M:/mnt;m:/media'
export NNN_PLUG="t:!st;m:mediainf;d:dragdrop;l:mimelist;p:preview-tabbed;o:organize;r:renamer;c:rsynccp;x:toggleex;u:umounttree;g:getplugs;s:x2sel;f:fzcd;2:dups;P:preview-tui;n:nmount,N:fixname;a:musicadd;z:musicrm"
export NNN_TRASH=1
export NNN_SSHFS="sshfs -o follow_symlinks"
export NNN_FIFO="/tmp/nnn.fifo.$(whoami)"
export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$"
# white color for files, default for the rest
export NNN_FCOLORS=c1e2272eff6033f7c6d6abc4
# for nnn's fzf plugin
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"

# fix for Java applications in dwm
export _JAVA_AWT_WM_NONREPARENTING=1

# fixing SVP won't picking up vapoursynth library
# TODO change 3.9 to whatever may be later
export PYTHONPATH=/usr/local/lib/python3.9/site-packages

# possibly Android stuff? why can't they honor XDG??
if [ -d "$HOME/platform-tools" ] ; then
    export PATH="$HOME/platform-tools:$PATH"
fi

# Changing pinentry for SSH logins
export GPG_TTY=$(tty)
if [[ -n "$SSH_CONNECTION" ]] ;then
    export PINENTRY_USER_DATA="USE_CURSES=1"
fi

source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/pass-completion"

# Git branch in prompt.
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ [\1]/'
}
export PS1="\[\e[01;36m\]\u@\h \[\e[01;32m\]\w\[\e[01;31m\]\$(parse_git_branch)\[\e[36m\] \$\[\e[00m\] "

# start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
