directory: ~/audio/music
library: ~/audio/beets.db

import:
  move: yes
  copy: no
  write: yes
  log: ~/.cache/beet/beets.log
  resume: ask

plugins: fetchart lastgenre ftintitle convert lyrics replaygain albumtypes embedart

paths:
  default: $albumartist/$album-$format/$disc-$track-$title
  singleton: singletons/$artist-$title
  comp: various-artists/$album%aunique{}-$format/$disc-$track-$title
  albumtype:soundtrack: soundtracks/$album-$format/$disc-$track-$title

convert:
  dest: ~/audio/music-phone
  copy_album_art: yes
  never_convert_lossy_files: yes
  embed: no
  max_bitrate: 1
  format: flac
  formats:
    flac:
      command: /home/ivan/audio/music-phone/convert-to-opus-if-not-blacklisted.sh $source $dest
      extension: opus

replaygain:
  auto: no
  backend: ffmpeg

embedart:
  auto: no
  remove_art_file: no
