directory: ~/audio/music
library: ~/.local/share/beet/beets.db

import:
  move: yes
  copy: no
  write: yes
  log: ~/.cache/beet/beets.log
  resume: ask


plugins: fetchart lastgenre

paths:
  default: $albumartist/$album-$format/$disc-$track-$title
  singleton: singletons/$artist-$title
  comp: various-artists/$album%aunique{}/$disc-$track-$title
  albumtype:soundtrack: soundtracks/$album/$disc-$track-$title
