directory: ~/audio/music
library: ~/audio/beets.db

import:
  move: yes
  copy: no
  write: yes
  log: ~/.cache/beets.log
  resume: ask

plugins: fetchart lastgenre ftintitle convert albumtypes embedart mbsync missing edit unimported VGMplug playlist scrub lyrics zero replaygain info

# albumtypes
paths:
  default: $albumartist/$album%aunique{}-$format/$disc-$track-$title
  singleton: singletons/$artist-$title
  comp: various-artists/$album%aunique{}-$format/$disc-$track-$title
  albumtype:soundtrack: soundtracks/$album%aunique{}-$format/$disc-$track-$title

convert:
  dest: ~/audio/music-phone
  copy_album_art: yes
  # album_art_maxwidth: 512
  embed: no
  max_bitrate: 1
  format: opus
  # quiet: true
  formats:
    opus:
      command: ffmpeg -i "$source" "$dest"

embedart:
  auto: no
  remove_art_file: no

fetchart:
  high_resolution: yes

playlist:
  auto: yes
  relative_to: ~/audio/music
  playlist_dir: ~/audio/playlists

ftintitle:
  drop: yes

zero:
  auto: yes
  # lyrics fetching is broken currently
  fields: lyrics

lyrics:
  auto: no

replaygain:
    backend: ffmpeg
